// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview This file defines a Genkit flow for categorizing transactions.
 *
 * - categorizeTransaction - A function that categorizes a transaction based on its description and past transactions.
 * - CategorizeTransactionInput - The input type for the categorizeTransaction function.
 * - CategorizeTransactionOutput - The return type for the categorizeTransaction function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CategorizeTransactionInputSchema = z.object({
  transactionDescription: z.string().describe('The description of the transaction.'),
  pastTransactions: z.array(z.object({
    description: z.string(),
    category: z.string(),
  })).describe('An array of past transactions with their descriptions and categories.'),
});
export type CategorizeTransactionInput = z.infer<typeof CategorizeTransactionInputSchema>;

const CategorizeTransactionOutputSchema = z.object({
  suggestedCategory: z.string().describe('The AI suggested category for the transaction.'),
  confidence: z.number().describe('The confidence level (0-1) of the AI in its category suggestion.'),
});
export type CategorizeTransactionOutput = z.infer<typeof CategorizeTransactionOutputSchema>;

export async function categorizeTransaction(input: CategorizeTransactionInput): Promise<CategorizeTransactionOutput> {
  return categorizeTransactionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'categorizeTransactionPrompt',
  input: {schema: CategorizeTransactionInputSchema},
  output: {schema: CategorizeTransactionOutputSchema},
  prompt: `You are an AI assistant that categorizes user transactions.

  Based on the transaction description and the user's past transactions, suggest a category for the transaction.
  Also provide a confidence level between 0 and 1 for your suggestion.

  Transaction Description: {{{transactionDescription}}}

  Past Transactions:
  {{#each pastTransactions}}
  - Description: {{{description}}}, Category: {{{category}}}
  {{/each}}
  `,
});

const categorizeTransactionFlow = ai.defineFlow(
  {
    name: 'categorizeTransactionFlow',
    inputSchema: CategorizeTransactionInputSchema,
    outputSchema: CategorizeTransactionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
